apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jumi-ah-dev

resources:
  - namespace.yaml
  - artifact-handoff.yaml

images:
  - name: artifact-handoff-image
    newName: artifact-handoff
    newTag: dev
