// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: api/proto/ah_v1.proto

package ahv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRef struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId    string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	ProducerNodeId string                 `protobuf:"bytes,2,opt,name=producer_node_id,json=producerNodeId,proto3" json:"producer_node_id,omitempty"`
	OutputName     string                 `protobuf:"bytes,3,opt,name=output_name,json=outputName,proto3" json:"output_name,omitempty"`
	ArtifactId     string                 `protobuf:"bytes,4,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Digest         string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeName       string                 `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Uri            string                 `protobuf:"bytes,7,opt,name=uri,proto3" json:"uri,omitempty"`
	SizeBytes      int64                  `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *ArtifactRef) GetProducerNodeId() string {
	if x != nil {
		return x.ProducerNodeId
	}
	return ""
}

func (x *ArtifactRef) GetOutputName() string {
	if x != nil {
		return x.OutputName
	}
	return ""
}

func (x *ArtifactRef) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ArtifactRef) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ArtifactRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

type RegisterArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactRef           `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterArtifactRequest) Reset() {
	*x = RegisterArtifactRequest{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterArtifactRequest) ProtoMessage() {}

func (x *RegisterArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterArtifactRequest.ProtoReflect.Descriptor instead.
func (*RegisterArtifactRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterArtifactRequest) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type RegisterArtifactResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AvailabilityState string                 `protobuf:"bytes,1,opt,name=availability_state,json=availabilityState,proto3" json:"availability_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterArtifactResponse) Reset() {
	*x = RegisterArtifactResponse{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterArtifactResponse) ProtoMessage() {}

func (x *RegisterArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterArtifactResponse.ProtoReflect.Descriptor instead.
func (*RegisterArtifactResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterArtifactResponse) GetAvailabilityState() string {
	if x != nil {
		return x.AvailabilityState
	}
	return ""
}

type ArtifactBinding struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BindingName        string                 `protobuf:"bytes,1,opt,name=binding_name,json=bindingName,proto3" json:"binding_name,omitempty"`
	SampleRunId        string                 `protobuf:"bytes,2,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	ChildNodeId        string                 `protobuf:"bytes,3,opt,name=child_node_id,json=childNodeId,proto3" json:"child_node_id,omitempty"`
	ChildInputName     string                 `protobuf:"bytes,4,opt,name=child_input_name,json=childInputName,proto3" json:"child_input_name,omitempty"`
	ProducerNodeId     string                 `protobuf:"bytes,5,opt,name=producer_node_id,json=producerNodeId,proto3" json:"producer_node_id,omitempty"`
	ProducerOutputName string                 `protobuf:"bytes,6,opt,name=producer_output_name,json=producerOutputName,proto3" json:"producer_output_name,omitempty"`
	ConsumePolicy      string                 `protobuf:"bytes,7,opt,name=consume_policy,json=consumePolicy,proto3" json:"consume_policy,omitempty"`
	Required           bool                   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	ExpectedDigest     string                 `protobuf:"bytes,9,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	ArtifactId         string                 `protobuf:"bytes,10,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArtifactBinding) Reset() {
	*x = ArtifactBinding{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactBinding) ProtoMessage() {}

func (x *ArtifactBinding) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactBinding.ProtoReflect.Descriptor instead.
func (*ArtifactBinding) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactBinding) GetBindingName() string {
	if x != nil {
		return x.BindingName
	}
	return ""
}

func (x *ArtifactBinding) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *ArtifactBinding) GetChildNodeId() string {
	if x != nil {
		return x.ChildNodeId
	}
	return ""
}

func (x *ArtifactBinding) GetChildInputName() string {
	if x != nil {
		return x.ChildInputName
	}
	return ""
}

func (x *ArtifactBinding) GetProducerNodeId() string {
	if x != nil {
		return x.ProducerNodeId
	}
	return ""
}

func (x *ArtifactBinding) GetProducerOutputName() string {
	if x != nil {
		return x.ProducerOutputName
	}
	return ""
}

func (x *ArtifactBinding) GetConsumePolicy() string {
	if x != nil {
		return x.ConsumePolicy
	}
	return ""
}

func (x *ArtifactBinding) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ArtifactBinding) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *ArtifactBinding) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

type ResolveHandoffRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Binding        *ArtifactBinding       `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	TargetNodeName string                 `protobuf:"bytes,2,opt,name=target_node_name,json=targetNodeName,proto3" json:"target_node_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveHandoffRequest) Reset() {
	*x = ResolveHandoffRequest{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHandoffRequest) ProtoMessage() {}

func (x *ResolveHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHandoffRequest.ProtoReflect.Descriptor instead.
func (*ResolveHandoffRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveHandoffRequest) GetBinding() *ArtifactBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *ResolveHandoffRequest) GetTargetNodeName() string {
	if x != nil {
		return x.TargetNodeName
	}
	return ""
}

type ResolveHandoffResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	ResolutionStatus        string                 `protobuf:"bytes,1,opt,name=resolution_status,json=resolutionStatus,proto3" json:"resolution_status,omitempty"`
	Decision                string                 `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	SourceNodeName          string                 `protobuf:"bytes,3,opt,name=source_node_name,json=sourceNodeName,proto3" json:"source_node_name,omitempty"`
	ArtifactUri             string                 `protobuf:"bytes,4,opt,name=artifact_uri,json=artifactUri,proto3" json:"artifact_uri,omitempty"`
	RequiresMaterialization bool                   `protobuf:"varint,5,opt,name=requires_materialization,json=requiresMaterialization,proto3" json:"requires_materialization,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ResolveHandoffResponse) Reset() {
	*x = ResolveHandoffResponse{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHandoffResponse) ProtoMessage() {}

func (x *ResolveHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHandoffResponse.ProtoReflect.Descriptor instead.
func (*ResolveHandoffResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveHandoffResponse) GetResolutionStatus() string {
	if x != nil {
		return x.ResolutionStatus
	}
	return ""
}

func (x *ResolveHandoffResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResolveHandoffResponse) GetSourceNodeName() string {
	if x != nil {
		return x.SourceNodeName
	}
	return ""
}

func (x *ResolveHandoffResponse) GetArtifactUri() string {
	if x != nil {
		return x.ArtifactUri
	}
	return ""
}

func (x *ResolveHandoffResponse) GetRequiresMaterialization() bool {
	if x != nil {
		return x.RequiresMaterialization
	}
	return false
}

type NotifyNodeTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TerminalState string                 `protobuf:"bytes,3,opt,name=terminal_state,json=terminalState,proto3" json:"terminal_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeTerminalRequest) Reset() {
	*x = NotifyNodeTerminalRequest{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeTerminalRequest) ProtoMessage() {}

func (x *NotifyNodeTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeTerminalRequest.ProtoReflect.Descriptor instead.
func (*NotifyNodeTerminalRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{6}
}

func (x *NotifyNodeTerminalRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *NotifyNodeTerminalRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NotifyNodeTerminalRequest) GetTerminalState() string {
	if x != nil {
		return x.TerminalState
	}
	return ""
}

type NotifyNodeTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeTerminalResponse) Reset() {
	*x = NotifyNodeTerminalResponse{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeTerminalResponse) ProtoMessage() {}

func (x *NotifyNodeTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeTerminalResponse.ProtoReflect.Descriptor instead.
func (*NotifyNodeTerminalResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{7}
}

func (x *NotifyNodeTerminalResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FinalizeSampleRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSampleRunRequest) Reset() {
	*x = FinalizeSampleRunRequest{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSampleRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSampleRunRequest) ProtoMessage() {}

func (x *FinalizeSampleRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSampleRunRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSampleRunRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{8}
}

func (x *FinalizeSampleRunRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

type FinalizeSampleRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSampleRunResponse) Reset() {
	*x = FinalizeSampleRunResponse{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSampleRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSampleRunResponse) ProtoMessage() {}

func (x *FinalizeSampleRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSampleRunResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSampleRunResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{9}
}

func (x *FinalizeSampleRunResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type EvaluateGCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateGCRequest) Reset() {
	*x = EvaluateGCRequest{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateGCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateGCRequest) ProtoMessage() {}

func (x *EvaluateGCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateGCRequest.ProtoReflect.Descriptor instead.
func (*EvaluateGCRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{10}
}

func (x *EvaluateGCRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

type EvaluateGCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateGCResponse) Reset() {
	*x = EvaluateGCResponse{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateGCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateGCResponse) ProtoMessage() {}

func (x *EvaluateGCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateGCResponse.ProtoReflect.Descriptor instead.
func (*EvaluateGCResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{11}
}

func (x *EvaluateGCResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetSampleRunLifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleRunLifecycleRequest) Reset() {
	*x = GetSampleRunLifecycleRequest{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleRunLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleRunLifecycleRequest) ProtoMessage() {}

func (x *GetSampleRunLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleRunLifecycleRequest.ProtoReflect.Descriptor instead.
func (*GetSampleRunLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{12}
}

func (x *GetSampleRunLifecycleRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

type GetSampleRunLifecycleResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId           string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	Finalized             bool                   `protobuf:"varint,2,opt,name=finalized,proto3" json:"finalized,omitempty"`
	FinalizedAt           string                 `protobuf:"bytes,3,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	RetentionPolicySource string                 `protobuf:"bytes,4,opt,name=retention_policy_source,json=retentionPolicySource,proto3" json:"retention_policy_source,omitempty"`
	RetentionDuration     string                 `protobuf:"bytes,5,opt,name=retention_duration,json=retentionDuration,proto3" json:"retention_duration,omitempty"`
	RetentionUntil        string                 `protobuf:"bytes,6,opt,name=retention_until,json=retentionUntil,proto3" json:"retention_until,omitempty"`
	GcEligible            bool                   `protobuf:"varint,7,opt,name=gc_eligible,json=gcEligible,proto3" json:"gc_eligible,omitempty"`
	GcEligibleAt          string                 `protobuf:"bytes,8,opt,name=gc_eligible_at,json=gcEligibleAt,proto3" json:"gc_eligible_at,omitempty"`
	GcBlockedReason       string                 `protobuf:"bytes,9,opt,name=gc_blocked_reason,json=gcBlockedReason,proto3" json:"gc_blocked_reason,omitempty"`
	TerminalNodeCount     int32                  `protobuf:"varint,10,opt,name=terminal_node_count,json=terminalNodeCount,proto3" json:"terminal_node_count,omitempty"`
	SucceededNodeCount    int32                  `protobuf:"varint,11,opt,name=succeeded_node_count,json=succeededNodeCount,proto3" json:"succeeded_node_count,omitempty"`
	FailedNodeCount       int32                  `protobuf:"varint,12,opt,name=failed_node_count,json=failedNodeCount,proto3" json:"failed_node_count,omitempty"`
	CanceledNodeCount     int32                  `protobuf:"varint,13,opt,name=canceled_node_count,json=canceledNodeCount,proto3" json:"canceled_node_count,omitempty"`
	RetainedArtifactCount int32                  `protobuf:"varint,14,opt,name=retained_artifact_count,json=retainedArtifactCount,proto3" json:"retained_artifact_count,omitempty"`
	RetainedArtifactBytes int64                  `protobuf:"varint,15,opt,name=retained_artifact_bytes,json=retainedArtifactBytes,proto3" json:"retained_artifact_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSampleRunLifecycleResponse) Reset() {
	*x = GetSampleRunLifecycleResponse{}
	mi := &file_api_proto_ah_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleRunLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleRunLifecycleResponse) ProtoMessage() {}

func (x *GetSampleRunLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_ah_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleRunLifecycleResponse.ProtoReflect.Descriptor instead.
func (*GetSampleRunLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_ah_v1_proto_rawDescGZIP(), []int{13}
}

func (x *GetSampleRunLifecycleResponse) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *GetSampleRunLifecycleResponse) GetFinalizedAt() string {
	if x != nil {
		return x.FinalizedAt
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetRetentionPolicySource() string {
	if x != nil {
		return x.RetentionPolicySource
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetRetentionDuration() string {
	if x != nil {
		return x.RetentionDuration
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetRetentionUntil() string {
	if x != nil {
		return x.RetentionUntil
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetGcEligible() bool {
	if x != nil {
		return x.GcEligible
	}
	return false
}

func (x *GetSampleRunLifecycleResponse) GetGcEligibleAt() string {
	if x != nil {
		return x.GcEligibleAt
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetGcBlockedReason() string {
	if x != nil {
		return x.GcBlockedReason
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetTerminalNodeCount() int32 {
	if x != nil {
		return x.TerminalNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetSucceededNodeCount() int32 {
	if x != nil {
		return x.SucceededNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetFailedNodeCount() int32 {
	if x != nil {
		return x.FailedNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetCanceledNodeCount() int32 {
	if x != nil {
		return x.CanceledNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetRetainedArtifactCount() int32 {
	if x != nil {
		return x.RetainedArtifactCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetRetainedArtifactBytes() int64 {
	if x != nil {
		return x.RetainedArtifactBytes
	}
	return 0
}

var File_api_proto_ah_v1_proto protoreflect.FileDescriptor

const file_api_proto_ah_v1_proto_rawDesc = "" +
	"\n" +
	"\x15api/proto/ah_v1.proto\x12\x05ah.v1\"\x83\x02\n" +
	"\vArtifactRef\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\x12(\n" +
	"\x10producer_node_id\x18\x02 \x01(\tR\x0eproducerNodeId\x12\x1f\n" +
	"\voutput_name\x18\x03 \x01(\tR\n" +
	"outputName\x12\x1f\n" +
	"\vartifact_id\x18\x04 \x01(\tR\n" +
	"artifactId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12\x1b\n" +
	"\tnode_name\x18\x06 \x01(\tR\bnodeName\x12\x10\n" +
	"\x03uri\x18\a \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x03R\tsizeBytes\"I\n" +
	"\x17RegisterArtifactRequest\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.ah.v1.ArtifactRefR\bartifact\"I\n" +
	"\x18RegisterArtifactResponse\x12-\n" +
	"\x12availability_state\x18\x01 \x01(\tR\x11availabilityState\"\x8f\x03\n" +
	"\x0fArtifactBinding\x12!\n" +
	"\fbinding_name\x18\x01 \x01(\tR\vbindingName\x12\"\n" +
	"\rsample_run_id\x18\x02 \x01(\tR\vsampleRunId\x12\"\n" +
	"\rchild_node_id\x18\x03 \x01(\tR\vchildNodeId\x12(\n" +
	"\x10child_input_name\x18\x04 \x01(\tR\x0echildInputName\x12(\n" +
	"\x10producer_node_id\x18\x05 \x01(\tR\x0eproducerNodeId\x120\n" +
	"\x14producer_output_name\x18\x06 \x01(\tR\x12producerOutputName\x12%\n" +
	"\x0econsume_policy\x18\a \x01(\tR\rconsumePolicy\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x12'\n" +
	"\x0fexpected_digest\x18\t \x01(\tR\x0eexpectedDigest\x12\x1f\n" +
	"\vartifact_id\x18\n" +
	" \x01(\tR\n" +
	"artifactId\"s\n" +
	"\x15ResolveHandoffRequest\x120\n" +
	"\abinding\x18\x01 \x01(\v2\x16.ah.v1.ArtifactBindingR\abinding\x12(\n" +
	"\x10target_node_name\x18\x02 \x01(\tR\x0etargetNodeName\"\xe9\x01\n" +
	"\x16ResolveHandoffResponse\x12+\n" +
	"\x11resolution_status\x18\x01 \x01(\tR\x10resolutionStatus\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12(\n" +
	"\x10source_node_name\x18\x03 \x01(\tR\x0esourceNodeName\x12!\n" +
	"\fartifact_uri\x18\x04 \x01(\tR\vartifactUri\x129\n" +
	"\x18requires_materialization\x18\x05 \x01(\bR\x17requiresMaterialization\"\x7f\n" +
	"\x19NotifyNodeTerminalRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eterminal_state\x18\x03 \x01(\tR\rterminalState\"8\n" +
	"\x1aNotifyNodeTerminalResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\">\n" +
	"\x18FinalizeSampleRunRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\"7\n" +
	"\x19FinalizeSampleRunResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"7\n" +
	"\x11EvaluateGCRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\"0\n" +
	"\x12EvaluateGCResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"B\n" +
	"\x1cGetSampleRunLifecycleRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\"\xb5\x05\n" +
	"\x1dGetSampleRunLifecycleResponse\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\x12\x1c\n" +
	"\tfinalized\x18\x02 \x01(\bR\tfinalized\x12!\n" +
	"\ffinalized_at\x18\x03 \x01(\tR\vfinalizedAt\x126\n" +
	"\x17retention_policy_source\x18\x04 \x01(\tR\x15retentionPolicySource\x12-\n" +
	"\x12retention_duration\x18\x05 \x01(\tR\x11retentionDuration\x12'\n" +
	"\x0fretention_until\x18\x06 \x01(\tR\x0eretentionUntil\x12\x1f\n" +
	"\vgc_eligible\x18\a \x01(\bR\n" +
	"gcEligible\x12$\n" +
	"\x0egc_eligible_at\x18\b \x01(\tR\fgcEligibleAt\x12*\n" +
	"\x11gc_blocked_reason\x18\t \x01(\tR\x0fgcBlockedReason\x12.\n" +
	"\x13terminal_node_count\x18\n" +
	" \x01(\x05R\x11terminalNodeCount\x120\n" +
	"\x14succeeded_node_count\x18\v \x01(\x05R\x12succeededNodeCount\x12*\n" +
	"\x11failed_node_count\x18\f \x01(\x05R\x0ffailedNodeCount\x12.\n" +
	"\x13canceled_node_count\x18\r \x01(\x05R\x11canceledNodeCount\x126\n" +
	"\x17retained_artifact_count\x18\x0e \x01(\x05R\x15retainedArtifactCount\x126\n" +
	"\x17retained_artifact_bytes\x18\x0f \x01(\x03R\x15retainedArtifactBytes2\x97\x04\n" +
	"\x17ArtifactHandoffResolver\x12S\n" +
	"\x10RegisterArtifact\x12\x1e.ah.v1.RegisterArtifactRequest\x1a\x1f.ah.v1.RegisterArtifactResponse\x12M\n" +
	"\x0eResolveHandoff\x12\x1c.ah.v1.ResolveHandoffRequest\x1a\x1d.ah.v1.ResolveHandoffResponse\x12Y\n" +
	"\x12NotifyNodeTerminal\x12 .ah.v1.NotifyNodeTerminalRequest\x1a!.ah.v1.NotifyNodeTerminalResponse\x12V\n" +
	"\x11FinalizeSampleRun\x12\x1f.ah.v1.FinalizeSampleRunRequest\x1a .ah.v1.FinalizeSampleRunResponse\x12A\n" +
	"\n" +
	"EvaluateGC\x12\x18.ah.v1.EvaluateGCRequest\x1a\x19.ah.v1.EvaluateGCResponse\x12b\n" +
	"\x15GetSampleRunLifecycle\x12#.ah.v1.GetSampleRunLifecycleRequest\x1a$.ah.v1.GetSampleRunLifecycleResponseB5Z3github.com/HeaInSeo/artifact-handoff/api/proto/ahv1b\x06proto3"

var (
	file_api_proto_ah_v1_proto_rawDescOnce sync.Once
	file_api_proto_ah_v1_proto_rawDescData []byte
)

func file_api_proto_ah_v1_proto_rawDescGZIP() []byte {
	file_api_proto_ah_v1_proto_rawDescOnce.Do(func() {
		file_api_proto_ah_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_ah_v1_proto_rawDesc), len(file_api_proto_ah_v1_proto_rawDesc)))
	})
	return file_api_proto_ah_v1_proto_rawDescData
}

var file_api_proto_ah_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_ah_v1_proto_goTypes = []any{
	(*ArtifactRef)(nil),                   // 0: ah.v1.ArtifactRef
	(*RegisterArtifactRequest)(nil),       // 1: ah.v1.RegisterArtifactRequest
	(*RegisterArtifactResponse)(nil),      // 2: ah.v1.RegisterArtifactResponse
	(*ArtifactBinding)(nil),               // 3: ah.v1.ArtifactBinding
	(*ResolveHandoffRequest)(nil),         // 4: ah.v1.ResolveHandoffRequest
	(*ResolveHandoffResponse)(nil),        // 5: ah.v1.ResolveHandoffResponse
	(*NotifyNodeTerminalRequest)(nil),     // 6: ah.v1.NotifyNodeTerminalRequest
	(*NotifyNodeTerminalResponse)(nil),    // 7: ah.v1.NotifyNodeTerminalResponse
	(*FinalizeSampleRunRequest)(nil),      // 8: ah.v1.FinalizeSampleRunRequest
	(*FinalizeSampleRunResponse)(nil),     // 9: ah.v1.FinalizeSampleRunResponse
	(*EvaluateGCRequest)(nil),             // 10: ah.v1.EvaluateGCRequest
	(*EvaluateGCResponse)(nil),            // 11: ah.v1.EvaluateGCResponse
	(*GetSampleRunLifecycleRequest)(nil),  // 12: ah.v1.GetSampleRunLifecycleRequest
	(*GetSampleRunLifecycleResponse)(nil), // 13: ah.v1.GetSampleRunLifecycleResponse
}
var file_api_proto_ah_v1_proto_depIdxs = []int32{
	0,  // 0: ah.v1.RegisterArtifactRequest.artifact:type_name -> ah.v1.ArtifactRef
	3,  // 1: ah.v1.ResolveHandoffRequest.binding:type_name -> ah.v1.ArtifactBinding
	1,  // 2: ah.v1.ArtifactHandoffResolver.RegisterArtifact:input_type -> ah.v1.RegisterArtifactRequest
	4,  // 3: ah.v1.ArtifactHandoffResolver.ResolveHandoff:input_type -> ah.v1.ResolveHandoffRequest
	6,  // 4: ah.v1.ArtifactHandoffResolver.NotifyNodeTerminal:input_type -> ah.v1.NotifyNodeTerminalRequest
	8,  // 5: ah.v1.ArtifactHandoffResolver.FinalizeSampleRun:input_type -> ah.v1.FinalizeSampleRunRequest
	10, // 6: ah.v1.ArtifactHandoffResolver.EvaluateGC:input_type -> ah.v1.EvaluateGCRequest
	12, // 7: ah.v1.ArtifactHandoffResolver.GetSampleRunLifecycle:input_type -> ah.v1.GetSampleRunLifecycleRequest
	2,  // 8: ah.v1.ArtifactHandoffResolver.RegisterArtifact:output_type -> ah.v1.RegisterArtifactResponse
	5,  // 9: ah.v1.ArtifactHandoffResolver.ResolveHandoff:output_type -> ah.v1.ResolveHandoffResponse
	7,  // 10: ah.v1.ArtifactHandoffResolver.NotifyNodeTerminal:output_type -> ah.v1.NotifyNodeTerminalResponse
	9,  // 11: ah.v1.ArtifactHandoffResolver.FinalizeSampleRun:output_type -> ah.v1.FinalizeSampleRunResponse
	11, // 12: ah.v1.ArtifactHandoffResolver.EvaluateGC:output_type -> ah.v1.EvaluateGCResponse
	13, // 13: ah.v1.ArtifactHandoffResolver.GetSampleRunLifecycle:output_type -> ah.v1.GetSampleRunLifecycleResponse
	8,  // [8:14] is the sub-list for method output_type
	2,  // [2:8] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_proto_ah_v1_proto_init() }
func file_api_proto_ah_v1_proto_init() {
	if File_api_proto_ah_v1_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_ah_v1_proto_rawDesc), len(file_api_proto_ah_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_ah_v1_proto_goTypes,
		DependencyIndexes: file_api_proto_ah_v1_proto_depIdxs,
		MessageInfos:      file_api_proto_ah_v1_proto_msgTypes,
	}.Build()
	File_api_proto_ah_v1_proto = out.File
	file_api_proto_ah_v1_proto_goTypes = nil
	file_api_proto_ah_v1_proto_depIdxs = nil
}
