// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: ah_v1.proto

// Field number assignment rules (enforced from first consumer integration):
//   - Field numbers must never be reused within a message, even if the original field is removed.
//   - Removing a field requires reserving its number: reserve 3; reserve "old_field_name";
//   - Breaking changes require a new package (ah.v2) or an explicit pre-v1 reset documented in git.
//   - See docs/CONTRACT_OWNERSHIP.md for the full contract policy.

package ahv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ArtifactRef struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId       string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	ProducerNodeId    string                 `protobuf:"bytes,2,opt,name=producer_node_id,json=producerNodeId,proto3" json:"producer_node_id,omitempty"`
	OutputName        string                 `protobuf:"bytes,3,opt,name=output_name,json=outputName,proto3" json:"output_name,omitempty"`
	ArtifactId        string                 `protobuf:"bytes,4,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	Digest            string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	NodeName          string                 `protobuf:"bytes,6,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Uri               string                 `protobuf:"bytes,7,opt,name=uri,proto3" json:"uri,omitempty"`
	SizeBytes         int64                  `protobuf:"varint,8,opt,name=size_bytes,json=sizeBytes,proto3" json:"size_bytes,omitempty"`
	ProducerAttemptId string                 `protobuf:"bytes,9,opt,name=producer_attempt_id,json=producerAttemptId,proto3" json:"producer_attempt_id,omitempty"`
	LogicalUri        string                 `protobuf:"bytes,10,opt,name=logical_uri,json=logicalUri,proto3" json:"logical_uri,omitempty"`
	Locations         []*ArtifactLocation    `protobuf:"bytes,11,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ArtifactRef) Reset() {
	*x = ArtifactRef{}
	mi := &file_ah_v1_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactRef) ProtoMessage() {}

func (x *ArtifactRef) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactRef.ProtoReflect.Descriptor instead.
func (*ArtifactRef) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{0}
}

func (x *ArtifactRef) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *ArtifactRef) GetProducerNodeId() string {
	if x != nil {
		return x.ProducerNodeId
	}
	return ""
}

func (x *ArtifactRef) GetOutputName() string {
	if x != nil {
		return x.OutputName
	}
	return ""
}

func (x *ArtifactRef) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactRef) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ArtifactRef) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *ArtifactRef) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *ArtifactRef) GetSizeBytes() int64 {
	if x != nil {
		return x.SizeBytes
	}
	return 0
}

func (x *ArtifactRef) GetProducerAttemptId() string {
	if x != nil {
		return x.ProducerAttemptId
	}
	return ""
}

func (x *ArtifactRef) GetLogicalUri() string {
	if x != nil {
		return x.LogicalUri
	}
	return ""
}

func (x *ArtifactRef) GetLocations() []*ArtifactLocation {
	if x != nil {
		return x.Locations
	}
	return nil
}

type RegisterArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Artifact      *ArtifactRef           `protobuf:"bytes,1,opt,name=artifact,proto3" json:"artifact,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterArtifactRequest) Reset() {
	*x = RegisterArtifactRequest{}
	mi := &file_ah_v1_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterArtifactRequest) ProtoMessage() {}

func (x *RegisterArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterArtifactRequest.ProtoReflect.Descriptor instead.
func (*RegisterArtifactRequest) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterArtifactRequest) GetArtifact() *ArtifactRef {
	if x != nil {
		return x.Artifact
	}
	return nil
}

type RegisterArtifactResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	AvailabilityState string                 `protobuf:"bytes,1,opt,name=availability_state,json=availabilityState,proto3" json:"availability_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RegisterArtifactResponse) Reset() {
	*x = RegisterArtifactResponse{}
	mi := &file_ah_v1_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterArtifactResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterArtifactResponse) ProtoMessage() {}

func (x *RegisterArtifactResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterArtifactResponse.ProtoReflect.Descriptor instead.
func (*RegisterArtifactResponse) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterArtifactResponse) GetAvailabilityState() string {
	if x != nil {
		return x.AvailabilityState
	}
	return ""
}

type ArtifactBinding struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	BindingName        string                 `protobuf:"bytes,1,opt,name=binding_name,json=bindingName,proto3" json:"binding_name,omitempty"`
	SampleRunId        string                 `protobuf:"bytes,2,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	ChildNodeId        string                 `protobuf:"bytes,3,opt,name=child_node_id,json=childNodeId,proto3" json:"child_node_id,omitempty"`
	ChildInputName     string                 `protobuf:"bytes,4,opt,name=child_input_name,json=childInputName,proto3" json:"child_input_name,omitempty"`
	ProducerNodeId     string                 `protobuf:"bytes,5,opt,name=producer_node_id,json=producerNodeId,proto3" json:"producer_node_id,omitempty"`
	ProducerOutputName string                 `protobuf:"bytes,6,opt,name=producer_output_name,json=producerOutputName,proto3" json:"producer_output_name,omitempty"`
	ConsumePolicy      string                 `protobuf:"bytes,7,opt,name=consume_policy,json=consumePolicy,proto3" json:"consume_policy,omitempty"`
	Required           bool                   `protobuf:"varint,8,opt,name=required,proto3" json:"required,omitempty"`
	ExpectedDigest     string                 `protobuf:"bytes,9,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	ArtifactId         string                 `protobuf:"bytes,10,opt,name=artifact_id,json=artifactId,proto3" json:"artifact_id,omitempty"`
	ProducerAttemptId  string                 `protobuf:"bytes,11,opt,name=producer_attempt_id,json=producerAttemptId,proto3" json:"producer_attempt_id,omitempty"`
	ChildAttemptId     string                 `protobuf:"bytes,12,opt,name=child_attempt_id,json=childAttemptId,proto3" json:"child_attempt_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ArtifactBinding) Reset() {
	*x = ArtifactBinding{}
	mi := &file_ah_v1_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactBinding) ProtoMessage() {}

func (x *ArtifactBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactBinding.ProtoReflect.Descriptor instead.
func (*ArtifactBinding) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{3}
}

func (x *ArtifactBinding) GetBindingName() string {
	if x != nil {
		return x.BindingName
	}
	return ""
}

func (x *ArtifactBinding) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *ArtifactBinding) GetChildNodeId() string {
	if x != nil {
		return x.ChildNodeId
	}
	return ""
}

func (x *ArtifactBinding) GetChildInputName() string {
	if x != nil {
		return x.ChildInputName
	}
	return ""
}

func (x *ArtifactBinding) GetProducerNodeId() string {
	if x != nil {
		return x.ProducerNodeId
	}
	return ""
}

func (x *ArtifactBinding) GetProducerOutputName() string {
	if x != nil {
		return x.ProducerOutputName
	}
	return ""
}

func (x *ArtifactBinding) GetConsumePolicy() string {
	if x != nil {
		return x.ConsumePolicy
	}
	return ""
}

func (x *ArtifactBinding) GetRequired() bool {
	if x != nil {
		return x.Required
	}
	return false
}

func (x *ArtifactBinding) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *ArtifactBinding) GetArtifactId() string {
	if x != nil {
		return x.ArtifactId
	}
	return ""
}

func (x *ArtifactBinding) GetProducerAttemptId() string {
	if x != nil {
		return x.ProducerAttemptId
	}
	return ""
}

func (x *ArtifactBinding) GetChildAttemptId() string {
	if x != nil {
		return x.ChildAttemptId
	}
	return ""
}

type ResolveHandoffRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Binding        *ArtifactBinding       `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	TargetNodeName string                 `protobuf:"bytes,2,opt,name=target_node_name,json=targetNodeName,proto3" json:"target_node_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveHandoffRequest) Reset() {
	*x = ResolveHandoffRequest{}
	mi := &file_ah_v1_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHandoffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHandoffRequest) ProtoMessage() {}

func (x *ResolveHandoffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHandoffRequest.ProtoReflect.Descriptor instead.
func (*ResolveHandoffRequest) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{4}
}

func (x *ResolveHandoffRequest) GetBinding() *ArtifactBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

func (x *ResolveHandoffRequest) GetTargetNodeName() string {
	if x != nil {
		return x.TargetNodeName
	}
	return ""
}

type PlacementIntent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mode          string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlacementIntent) Reset() {
	*x = PlacementIntent{}
	mi := &file_ah_v1_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlacementIntent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlacementIntent) ProtoMessage() {}

func (x *PlacementIntent) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlacementIntent.ProtoReflect.Descriptor instead.
func (*PlacementIntent) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{5}
}

func (x *PlacementIntent) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *PlacementIntent) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type NodeLocalLocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeName      string                 `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeLocalLocation) Reset() {
	*x = NodeLocalLocation{}
	mi := &file_ah_v1_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeLocalLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeLocalLocation) ProtoMessage() {}

func (x *NodeLocalLocation) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeLocalLocation.ProtoReflect.Descriptor instead.
func (*NodeLocalLocation) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{6}
}

func (x *NodeLocalLocation) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *NodeLocalLocation) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

type HttpSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpSource) Reset() {
	*x = HttpSource{}
	mi := &file_ah_v1_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpSource) ProtoMessage() {}

func (x *HttpSource) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpSource.ProtoReflect.Descriptor instead.
func (*HttpSource) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{7}
}

func (x *HttpSource) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type ArtifactLocation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Backend:
	//
	//	*ArtifactLocation_NodeLocal
	//	*ArtifactLocation_Http
	Backend       isArtifactLocation_Backend `protobuf_oneof:"backend"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactLocation) Reset() {
	*x = ArtifactLocation{}
	mi := &file_ah_v1_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactLocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactLocation) ProtoMessage() {}

func (x *ArtifactLocation) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactLocation.ProtoReflect.Descriptor instead.
func (*ArtifactLocation) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{8}
}

func (x *ArtifactLocation) GetBackend() isArtifactLocation_Backend {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *ArtifactLocation) GetNodeLocal() *NodeLocalLocation {
	if x != nil {
		if x, ok := x.Backend.(*ArtifactLocation_NodeLocal); ok {
			return x.NodeLocal
		}
	}
	return nil
}

func (x *ArtifactLocation) GetHttp() *HttpSource {
	if x != nil {
		if x, ok := x.Backend.(*ArtifactLocation_Http); ok {
			return x.Http
		}
	}
	return nil
}

type isArtifactLocation_Backend interface {
	isArtifactLocation_Backend()
}

type ArtifactLocation_NodeLocal struct {
	NodeLocal *NodeLocalLocation `protobuf:"bytes,1,opt,name=node_local,json=nodeLocal,proto3,oneof"`
}

type ArtifactLocation_Http struct {
	Http *HttpSource `protobuf:"bytes,2,opt,name=http,proto3,oneof"`
}

func (*ArtifactLocation_NodeLocal) isArtifactLocation_Backend() {}

func (*ArtifactLocation_Http) isArtifactLocation_Backend() {}

type MaterializationPlan struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Mode              string                 `protobuf:"bytes,1,opt,name=mode,proto3" json:"mode,omitempty"`
	Uri               string                 `protobuf:"bytes,2,opt,name=uri,proto3" json:"uri,omitempty"`
	ExpectedDigest    string                 `protobuf:"bytes,3,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	ExpectedSizeBytes int64                  `protobuf:"varint,4,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3" json:"expected_size_bytes,omitempty"`
	SourceLocation    *ArtifactLocation      `protobuf:"bytes,5,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	LocalPath         string                 `protobuf:"bytes,6,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MaterializationPlan) Reset() {
	*x = MaterializationPlan{}
	mi := &file_ah_v1_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationPlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationPlan) ProtoMessage() {}

func (x *MaterializationPlan) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationPlan.ProtoReflect.Descriptor instead.
func (*MaterializationPlan) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{9}
}

func (x *MaterializationPlan) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MaterializationPlan) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MaterializationPlan) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *MaterializationPlan) GetExpectedSizeBytes() int64 {
	if x != nil {
		return x.ExpectedSizeBytes
	}
	return 0
}

func (x *MaterializationPlan) GetSourceLocation() *ArtifactLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *MaterializationPlan) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

type MaterializationCondition struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	NodeName      string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	BackendId     string                 `protobuf:"bytes,3,opt,name=backend_id,json=backendId,proto3" json:"backend_id,omitempty"`
	SourceRef     string                 `protobuf:"bytes,4,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MaterializationCondition) Reset() {
	*x = MaterializationCondition{}
	mi := &file_ah_v1_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationCondition) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationCondition) ProtoMessage() {}

func (x *MaterializationCondition) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationCondition.ProtoReflect.Descriptor instead.
func (*MaterializationCondition) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{10}
}

func (x *MaterializationCondition) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *MaterializationCondition) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *MaterializationCondition) GetBackendId() string {
	if x != nil {
		return x.BackendId
	}
	return ""
}

func (x *MaterializationCondition) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *MaterializationCondition) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

type MaterializationCandidate struct {
	state             protoimpl.MessageState      `protogen:"open.v1"`
	Priority          int32                       `protobuf:"varint,1,opt,name=priority,proto3" json:"priority,omitempty"`
	Mode              string                      `protobuf:"bytes,2,opt,name=mode,proto3" json:"mode,omitempty"`
	SourceRef         string                      `protobuf:"bytes,3,opt,name=source_ref,json=sourceRef,proto3" json:"source_ref,omitempty"`
	ExpectedDigest    string                      `protobuf:"bytes,4,opt,name=expected_digest,json=expectedDigest,proto3" json:"expected_digest,omitempty"`
	ExpectedSizeBytes int64                       `protobuf:"varint,5,opt,name=expected_size_bytes,json=expectedSizeBytes,proto3" json:"expected_size_bytes,omitempty"`
	LocalPath         string                      `protobuf:"bytes,6,opt,name=local_path,json=localPath,proto3" json:"local_path,omitempty"`
	SourceLocation    *ArtifactLocation           `protobuf:"bytes,7,opt,name=source_location,json=sourceLocation,proto3" json:"source_location,omitempty"`
	Uri               string                      `protobuf:"bytes,8,opt,name=uri,proto3" json:"uri,omitempty"`
	Conditions        []*MaterializationCondition `protobuf:"bytes,9,rep,name=conditions,proto3" json:"conditions,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MaterializationCandidate) Reset() {
	*x = MaterializationCandidate{}
	mi := &file_ah_v1_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MaterializationCandidate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MaterializationCandidate) ProtoMessage() {}

func (x *MaterializationCandidate) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MaterializationCandidate.ProtoReflect.Descriptor instead.
func (*MaterializationCandidate) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{11}
}

func (x *MaterializationCandidate) GetPriority() int32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *MaterializationCandidate) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *MaterializationCandidate) GetSourceRef() string {
	if x != nil {
		return x.SourceRef
	}
	return ""
}

func (x *MaterializationCandidate) GetExpectedDigest() string {
	if x != nil {
		return x.ExpectedDigest
	}
	return ""
}

func (x *MaterializationCandidate) GetExpectedSizeBytes() int64 {
	if x != nil {
		return x.ExpectedSizeBytes
	}
	return 0
}

func (x *MaterializationCandidate) GetLocalPath() string {
	if x != nil {
		return x.LocalPath
	}
	return ""
}

func (x *MaterializationCandidate) GetSourceLocation() *ArtifactLocation {
	if x != nil {
		return x.SourceLocation
	}
	return nil
}

func (x *MaterializationCandidate) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

func (x *MaterializationCandidate) GetConditions() []*MaterializationCondition {
	if x != nil {
		return x.Conditions
	}
	return nil
}

type ResolveHandoffResponse struct {
	state                     protoimpl.MessageState      `protogen:"open.v1"`
	ResolutionStatus          string                      `protobuf:"bytes,1,opt,name=resolution_status,json=resolutionStatus,proto3" json:"resolution_status,omitempty"`
	Decision                  string                      `protobuf:"bytes,2,opt,name=decision,proto3" json:"decision,omitempty"`
	PlacementIntent           *PlacementIntent            `protobuf:"bytes,3,opt,name=placement_intent,json=placementIntent,proto3" json:"placement_intent,omitempty"`
	MaterializationPlan       *MaterializationPlan        `protobuf:"bytes,4,opt,name=materialization_plan,json=materializationPlan,proto3" json:"materialization_plan,omitempty"`
	Reason                    string                      `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	Retryable                 bool                        `protobuf:"varint,6,opt,name=retryable,proto3" json:"retryable,omitempty"`
	MaterializationCandidates []*MaterializationCandidate `protobuf:"bytes,7,rep,name=materialization_candidates,json=materializationCandidates,proto3" json:"materialization_candidates,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *ResolveHandoffResponse) Reset() {
	*x = ResolveHandoffResponse{}
	mi := &file_ah_v1_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveHandoffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveHandoffResponse) ProtoMessage() {}

func (x *ResolveHandoffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveHandoffResponse.ProtoReflect.Descriptor instead.
func (*ResolveHandoffResponse) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{12}
}

func (x *ResolveHandoffResponse) GetResolutionStatus() string {
	if x != nil {
		return x.ResolutionStatus
	}
	return ""
}

func (x *ResolveHandoffResponse) GetDecision() string {
	if x != nil {
		return x.Decision
	}
	return ""
}

func (x *ResolveHandoffResponse) GetPlacementIntent() *PlacementIntent {
	if x != nil {
		return x.PlacementIntent
	}
	return nil
}

func (x *ResolveHandoffResponse) GetMaterializationPlan() *MaterializationPlan {
	if x != nil {
		return x.MaterializationPlan
	}
	return nil
}

func (x *ResolveHandoffResponse) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ResolveHandoffResponse) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

func (x *ResolveHandoffResponse) GetMaterializationCandidates() []*MaterializationCandidate {
	if x != nil {
		return x.MaterializationCandidates
	}
	return nil
}

type NotifyNodeTerminalRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	TerminalState string                 `protobuf:"bytes,3,opt,name=terminal_state,json=terminalState,proto3" json:"terminal_state,omitempty"`
	AttemptId     string                 `protobuf:"bytes,4,opt,name=attempt_id,json=attemptId,proto3" json:"attempt_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeTerminalRequest) Reset() {
	*x = NotifyNodeTerminalRequest{}
	mi := &file_ah_v1_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeTerminalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeTerminalRequest) ProtoMessage() {}

func (x *NotifyNodeTerminalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeTerminalRequest.ProtoReflect.Descriptor instead.
func (*NotifyNodeTerminalRequest) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{13}
}

func (x *NotifyNodeTerminalRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *NotifyNodeTerminalRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *NotifyNodeTerminalRequest) GetTerminalState() string {
	if x != nil {
		return x.TerminalState
	}
	return ""
}

func (x *NotifyNodeTerminalRequest) GetAttemptId() string {
	if x != nil {
		return x.AttemptId
	}
	return ""
}

type NotifyNodeTerminalResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotifyNodeTerminalResponse) Reset() {
	*x = NotifyNodeTerminalResponse{}
	mi := &file_ah_v1_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotifyNodeTerminalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotifyNodeTerminalResponse) ProtoMessage() {}

func (x *NotifyNodeTerminalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotifyNodeTerminalResponse.ProtoReflect.Descriptor instead.
func (*NotifyNodeTerminalResponse) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{14}
}

func (x *NotifyNodeTerminalResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type FinalizeSampleRunRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSampleRunRequest) Reset() {
	*x = FinalizeSampleRunRequest{}
	mi := &file_ah_v1_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSampleRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSampleRunRequest) ProtoMessage() {}

func (x *FinalizeSampleRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSampleRunRequest.ProtoReflect.Descriptor instead.
func (*FinalizeSampleRunRequest) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{15}
}

func (x *FinalizeSampleRunRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

type FinalizeSampleRunResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeSampleRunResponse) Reset() {
	*x = FinalizeSampleRunResponse{}
	mi := &file_ah_v1_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeSampleRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeSampleRunResponse) ProtoMessage() {}

func (x *FinalizeSampleRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeSampleRunResponse.ProtoReflect.Descriptor instead.
func (*FinalizeSampleRunResponse) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{16}
}

func (x *FinalizeSampleRunResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type EvaluateGCRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateGCRequest) Reset() {
	*x = EvaluateGCRequest{}
	mi := &file_ah_v1_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateGCRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateGCRequest) ProtoMessage() {}

func (x *EvaluateGCRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateGCRequest.ProtoReflect.Descriptor instead.
func (*EvaluateGCRequest) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{17}
}

func (x *EvaluateGCRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

type EvaluateGCResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accepted      bool                   `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EvaluateGCResponse) Reset() {
	*x = EvaluateGCResponse{}
	mi := &file_ah_v1_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateGCResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateGCResponse) ProtoMessage() {}

func (x *EvaluateGCResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateGCResponse.ProtoReflect.Descriptor instead.
func (*EvaluateGCResponse) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{18}
}

func (x *EvaluateGCResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

type GetSampleRunLifecycleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId   string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSampleRunLifecycleRequest) Reset() {
	*x = GetSampleRunLifecycleRequest{}
	mi := &file_ah_v1_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleRunLifecycleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleRunLifecycleRequest) ProtoMessage() {}

func (x *GetSampleRunLifecycleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleRunLifecycleRequest.ProtoReflect.Descriptor instead.
func (*GetSampleRunLifecycleRequest) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{19}
}

func (x *GetSampleRunLifecycleRequest) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

type GetSampleRunLifecycleResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	SampleRunId           string                 `protobuf:"bytes,1,opt,name=sample_run_id,json=sampleRunId,proto3" json:"sample_run_id,omitempty"`
	Finalized             bool                   `protobuf:"varint,2,opt,name=finalized,proto3" json:"finalized,omitempty"`
	FinalizedAt           string                 `protobuf:"bytes,3,opt,name=finalized_at,json=finalizedAt,proto3" json:"finalized_at,omitempty"`
	RetentionPolicySource string                 `protobuf:"bytes,4,opt,name=retention_policy_source,json=retentionPolicySource,proto3" json:"retention_policy_source,omitempty"`
	RetentionDuration     string                 `protobuf:"bytes,5,opt,name=retention_duration,json=retentionDuration,proto3" json:"retention_duration,omitempty"`
	RetentionUntil        string                 `protobuf:"bytes,6,opt,name=retention_until,json=retentionUntil,proto3" json:"retention_until,omitempty"`
	GcEligible            bool                   `protobuf:"varint,7,opt,name=gc_eligible,json=gcEligible,proto3" json:"gc_eligible,omitempty"`
	GcEligibleAt          string                 `protobuf:"bytes,8,opt,name=gc_eligible_at,json=gcEligibleAt,proto3" json:"gc_eligible_at,omitempty"`
	GcBlockedReason       string                 `protobuf:"bytes,9,opt,name=gc_blocked_reason,json=gcBlockedReason,proto3" json:"gc_blocked_reason,omitempty"`
	TerminalNodeCount     int32                  `protobuf:"varint,10,opt,name=terminal_node_count,json=terminalNodeCount,proto3" json:"terminal_node_count,omitempty"`
	SucceededNodeCount    int32                  `protobuf:"varint,11,opt,name=succeeded_node_count,json=succeededNodeCount,proto3" json:"succeeded_node_count,omitempty"`
	FailedNodeCount       int32                  `protobuf:"varint,12,opt,name=failed_node_count,json=failedNodeCount,proto3" json:"failed_node_count,omitempty"`
	CanceledNodeCount     int32                  `protobuf:"varint,13,opt,name=canceled_node_count,json=canceledNodeCount,proto3" json:"canceled_node_count,omitempty"`
	RetainedArtifactCount int32                  `protobuf:"varint,14,opt,name=retained_artifact_count,json=retainedArtifactCount,proto3" json:"retained_artifact_count,omitempty"`
	RetainedArtifactBytes int64                  `protobuf:"varint,15,opt,name=retained_artifact_bytes,json=retainedArtifactBytes,proto3" json:"retained_artifact_bytes,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetSampleRunLifecycleResponse) Reset() {
	*x = GetSampleRunLifecycleResponse{}
	mi := &file_ah_v1_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSampleRunLifecycleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSampleRunLifecycleResponse) ProtoMessage() {}

func (x *GetSampleRunLifecycleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ah_v1_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSampleRunLifecycleResponse.ProtoReflect.Descriptor instead.
func (*GetSampleRunLifecycleResponse) Descriptor() ([]byte, []int) {
	return file_ah_v1_proto_rawDescGZIP(), []int{20}
}

func (x *GetSampleRunLifecycleResponse) GetSampleRunId() string {
	if x != nil {
		return x.SampleRunId
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetFinalized() bool {
	if x != nil {
		return x.Finalized
	}
	return false
}

func (x *GetSampleRunLifecycleResponse) GetFinalizedAt() string {
	if x != nil {
		return x.FinalizedAt
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetRetentionPolicySource() string {
	if x != nil {
		return x.RetentionPolicySource
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetRetentionDuration() string {
	if x != nil {
		return x.RetentionDuration
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetRetentionUntil() string {
	if x != nil {
		return x.RetentionUntil
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetGcEligible() bool {
	if x != nil {
		return x.GcEligible
	}
	return false
}

func (x *GetSampleRunLifecycleResponse) GetGcEligibleAt() string {
	if x != nil {
		return x.GcEligibleAt
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetGcBlockedReason() string {
	if x != nil {
		return x.GcBlockedReason
	}
	return ""
}

func (x *GetSampleRunLifecycleResponse) GetTerminalNodeCount() int32 {
	if x != nil {
		return x.TerminalNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetSucceededNodeCount() int32 {
	if x != nil {
		return x.SucceededNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetFailedNodeCount() int32 {
	if x != nil {
		return x.FailedNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetCanceledNodeCount() int32 {
	if x != nil {
		return x.CanceledNodeCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetRetainedArtifactCount() int32 {
	if x != nil {
		return x.RetainedArtifactCount
	}
	return 0
}

func (x *GetSampleRunLifecycleResponse) GetRetainedArtifactBytes() int64 {
	if x != nil {
		return x.RetainedArtifactBytes
	}
	return 0
}

var File_ah_v1_proto protoreflect.FileDescriptor

const file_ah_v1_proto_rawDesc = "" +
	"\n" +
	"\vah_v1.proto\x12\x05ah.v1\"\x8b\x03\n" +
	"\vArtifactRef\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\x12(\n" +
	"\x10producer_node_id\x18\x02 \x01(\tR\x0eproducerNodeId\x12\x1f\n" +
	"\voutput_name\x18\x03 \x01(\tR\n" +
	"outputName\x12\x1f\n" +
	"\vartifact_id\x18\x04 \x01(\tR\n" +
	"artifactId\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12\x1b\n" +
	"\tnode_name\x18\x06 \x01(\tR\bnodeName\x12\x10\n" +
	"\x03uri\x18\a \x01(\tR\x03uri\x12\x1d\n" +
	"\n" +
	"size_bytes\x18\b \x01(\x03R\tsizeBytes\x12.\n" +
	"\x13producer_attempt_id\x18\t \x01(\tR\x11producerAttemptId\x12\x1f\n" +
	"\vlogical_uri\x18\n" +
	" \x01(\tR\n" +
	"logicalUri\x125\n" +
	"\tlocations\x18\v \x03(\v2\x17.ah.v1.ArtifactLocationR\tlocations\"I\n" +
	"\x17RegisterArtifactRequest\x12.\n" +
	"\bartifact\x18\x01 \x01(\v2\x12.ah.v1.ArtifactRefR\bartifact\"I\n" +
	"\x18RegisterArtifactResponse\x12-\n" +
	"\x12availability_state\x18\x01 \x01(\tR\x11availabilityState\"\xe9\x03\n" +
	"\x0fArtifactBinding\x12!\n" +
	"\fbinding_name\x18\x01 \x01(\tR\vbindingName\x12\"\n" +
	"\rsample_run_id\x18\x02 \x01(\tR\vsampleRunId\x12\"\n" +
	"\rchild_node_id\x18\x03 \x01(\tR\vchildNodeId\x12(\n" +
	"\x10child_input_name\x18\x04 \x01(\tR\x0echildInputName\x12(\n" +
	"\x10producer_node_id\x18\x05 \x01(\tR\x0eproducerNodeId\x120\n" +
	"\x14producer_output_name\x18\x06 \x01(\tR\x12producerOutputName\x12%\n" +
	"\x0econsume_policy\x18\a \x01(\tR\rconsumePolicy\x12\x1a\n" +
	"\brequired\x18\b \x01(\bR\brequired\x12'\n" +
	"\x0fexpected_digest\x18\t \x01(\tR\x0eexpectedDigest\x12\x1f\n" +
	"\vartifact_id\x18\n" +
	" \x01(\tR\n" +
	"artifactId\x12.\n" +
	"\x13producer_attempt_id\x18\v \x01(\tR\x11producerAttemptId\x12(\n" +
	"\x10child_attempt_id\x18\f \x01(\tR\x0echildAttemptId\"s\n" +
	"\x15ResolveHandoffRequest\x120\n" +
	"\abinding\x18\x01 \x01(\v2\x16.ah.v1.ArtifactBindingR\abinding\x12(\n" +
	"\x10target_node_name\x18\x02 \x01(\tR\x0etargetNodeName\"B\n" +
	"\x0fPlacementIntent\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\"D\n" +
	"\x11NodeLocalLocation\x12\x1b\n" +
	"\tnode_name\x18\x01 \x01(\tR\bnodeName\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\"\x1e\n" +
	"\n" +
	"HttpSource\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"\x81\x01\n" +
	"\x10ArtifactLocation\x129\n" +
	"\n" +
	"node_local\x18\x01 \x01(\v2\x18.ah.v1.NodeLocalLocationH\x00R\tnodeLocal\x12'\n" +
	"\x04http\x18\x02 \x01(\v2\x11.ah.v1.HttpSourceH\x00R\x04httpB\t\n" +
	"\abackend\"\xf5\x01\n" +
	"\x13MaterializationPlan\x12\x12\n" +
	"\x04mode\x18\x01 \x01(\tR\x04mode\x12\x10\n" +
	"\x03uri\x18\x02 \x01(\tR\x03uri\x12'\n" +
	"\x0fexpected_digest\x18\x03 \x01(\tR\x0eexpectedDigest\x12.\n" +
	"\x13expected_size_bytes\x18\x04 \x01(\x03R\x11expectedSizeBytes\x12@\n" +
	"\x0fsource_location\x18\x05 \x01(\v2\x17.ah.v1.ArtifactLocationR\x0esourceLocation\x12\x1d\n" +
	"\n" +
	"local_path\x18\x06 \x01(\tR\tlocalPath\"\x9f\x01\n" +
	"\x18MaterializationCondition\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1b\n" +
	"\tnode_name\x18\x02 \x01(\tR\bnodeName\x12\x1d\n" +
	"\n" +
	"backend_id\x18\x03 \x01(\tR\tbackendId\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x04 \x01(\tR\tsourceRef\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\"\xf6\x02\n" +
	"\x18MaterializationCandidate\x12\x1a\n" +
	"\bpriority\x18\x01 \x01(\x05R\bpriority\x12\x12\n" +
	"\x04mode\x18\x02 \x01(\tR\x04mode\x12\x1d\n" +
	"\n" +
	"source_ref\x18\x03 \x01(\tR\tsourceRef\x12'\n" +
	"\x0fexpected_digest\x18\x04 \x01(\tR\x0eexpectedDigest\x12.\n" +
	"\x13expected_size_bytes\x18\x05 \x01(\x03R\x11expectedSizeBytes\x12\x1d\n" +
	"\n" +
	"local_path\x18\x06 \x01(\tR\tlocalPath\x12@\n" +
	"\x0fsource_location\x18\a \x01(\v2\x17.ah.v1.ArtifactLocationR\x0esourceLocation\x12\x10\n" +
	"\x03uri\x18\b \x01(\tR\x03uri\x12?\n" +
	"\n" +
	"conditions\x18\t \x03(\v2\x1f.ah.v1.MaterializationConditionR\n" +
	"conditions\"\xc3\x03\n" +
	"\x16ResolveHandoffResponse\x12+\n" +
	"\x11resolution_status\x18\x01 \x01(\tR\x10resolutionStatus\x12\x1a\n" +
	"\bdecision\x18\x02 \x01(\tR\bdecision\x12A\n" +
	"\x10placement_intent\x18\x03 \x01(\v2\x16.ah.v1.PlacementIntentR\x0fplacementIntent\x12M\n" +
	"\x14materialization_plan\x18\x04 \x01(\v2\x1a.ah.v1.MaterializationPlanR\x13materializationPlan\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\x12\x1c\n" +
	"\tretryable\x18\x06 \x01(\bR\tretryable\x12^\n" +
	"\x1amaterialization_candidates\x18\a \x03(\v2\x1f.ah.v1.MaterializationCandidateR\x19materializationCandidatesR\x10source_node_nameR\fartifact_uriR\x18requires_materialization\"\x9e\x01\n" +
	"\x19NotifyNodeTerminalRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId\x12%\n" +
	"\x0eterminal_state\x18\x03 \x01(\tR\rterminalState\x12\x1d\n" +
	"\n" +
	"attempt_id\x18\x04 \x01(\tR\tattemptId\"8\n" +
	"\x1aNotifyNodeTerminalResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\">\n" +
	"\x18FinalizeSampleRunRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\"7\n" +
	"\x19FinalizeSampleRunResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"7\n" +
	"\x11EvaluateGCRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\"0\n" +
	"\x12EvaluateGCResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\"B\n" +
	"\x1cGetSampleRunLifecycleRequest\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\"\xb5\x05\n" +
	"\x1dGetSampleRunLifecycleResponse\x12\"\n" +
	"\rsample_run_id\x18\x01 \x01(\tR\vsampleRunId\x12\x1c\n" +
	"\tfinalized\x18\x02 \x01(\bR\tfinalized\x12!\n" +
	"\ffinalized_at\x18\x03 \x01(\tR\vfinalizedAt\x126\n" +
	"\x17retention_policy_source\x18\x04 \x01(\tR\x15retentionPolicySource\x12-\n" +
	"\x12retention_duration\x18\x05 \x01(\tR\x11retentionDuration\x12'\n" +
	"\x0fretention_until\x18\x06 \x01(\tR\x0eretentionUntil\x12\x1f\n" +
	"\vgc_eligible\x18\a \x01(\bR\n" +
	"gcEligible\x12$\n" +
	"\x0egc_eligible_at\x18\b \x01(\tR\fgcEligibleAt\x12*\n" +
	"\x11gc_blocked_reason\x18\t \x01(\tR\x0fgcBlockedReason\x12.\n" +
	"\x13terminal_node_count\x18\n" +
	" \x01(\x05R\x11terminalNodeCount\x120\n" +
	"\x14succeeded_node_count\x18\v \x01(\x05R\x12succeededNodeCount\x12*\n" +
	"\x11failed_node_count\x18\f \x01(\x05R\x0ffailedNodeCount\x12.\n" +
	"\x13canceled_node_count\x18\r \x01(\x05R\x11canceledNodeCount\x126\n" +
	"\x17retained_artifact_count\x18\x0e \x01(\x05R\x15retainedArtifactCount\x126\n" +
	"\x17retained_artifact_bytes\x18\x0f \x01(\x03R\x15retainedArtifactBytes2\x97\x04\n" +
	"\x17ArtifactHandoffResolver\x12S\n" +
	"\x10RegisterArtifact\x12\x1e.ah.v1.RegisterArtifactRequest\x1a\x1f.ah.v1.RegisterArtifactResponse\x12M\n" +
	"\x0eResolveHandoff\x12\x1c.ah.v1.ResolveHandoffRequest\x1a\x1d.ah.v1.ResolveHandoffResponse\x12Y\n" +
	"\x12NotifyNodeTerminal\x12 .ah.v1.NotifyNodeTerminalRequest\x1a!.ah.v1.NotifyNodeTerminalResponse\x12V\n" +
	"\x11FinalizeSampleRun\x12\x1f.ah.v1.FinalizeSampleRunRequest\x1a .ah.v1.FinalizeSampleRunResponse\x12A\n" +
	"\n" +
	"EvaluateGC\x12\x18.ah.v1.EvaluateGCRequest\x1a\x19.ah.v1.EvaluateGCResponse\x12b\n" +
	"\x15GetSampleRunLifecycle\x12#.ah.v1.GetSampleRunLifecycleRequest\x1a$.ah.v1.GetSampleRunLifecycleResponseB5Z3github.com/HeaInSeo/artifact-handoff/api/proto/ahv1b\x06proto3"

var (
	file_ah_v1_proto_rawDescOnce sync.Once
	file_ah_v1_proto_rawDescData []byte
)

func file_ah_v1_proto_rawDescGZIP() []byte {
	file_ah_v1_proto_rawDescOnce.Do(func() {
		file_ah_v1_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ah_v1_proto_rawDesc), len(file_ah_v1_proto_rawDesc)))
	})
	return file_ah_v1_proto_rawDescData
}

var file_ah_v1_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_ah_v1_proto_goTypes = []any{
	(*ArtifactRef)(nil),                   // 0: ah.v1.ArtifactRef
	(*RegisterArtifactRequest)(nil),       // 1: ah.v1.RegisterArtifactRequest
	(*RegisterArtifactResponse)(nil),      // 2: ah.v1.RegisterArtifactResponse
	(*ArtifactBinding)(nil),               // 3: ah.v1.ArtifactBinding
	(*ResolveHandoffRequest)(nil),         // 4: ah.v1.ResolveHandoffRequest
	(*PlacementIntent)(nil),               // 5: ah.v1.PlacementIntent
	(*NodeLocalLocation)(nil),             // 6: ah.v1.NodeLocalLocation
	(*HttpSource)(nil),                    // 7: ah.v1.HttpSource
	(*ArtifactLocation)(nil),              // 8: ah.v1.ArtifactLocation
	(*MaterializationPlan)(nil),           // 9: ah.v1.MaterializationPlan
	(*MaterializationCondition)(nil),      // 10: ah.v1.MaterializationCondition
	(*MaterializationCandidate)(nil),      // 11: ah.v1.MaterializationCandidate
	(*ResolveHandoffResponse)(nil),        // 12: ah.v1.ResolveHandoffResponse
	(*NotifyNodeTerminalRequest)(nil),     // 13: ah.v1.NotifyNodeTerminalRequest
	(*NotifyNodeTerminalResponse)(nil),    // 14: ah.v1.NotifyNodeTerminalResponse
	(*FinalizeSampleRunRequest)(nil),      // 15: ah.v1.FinalizeSampleRunRequest
	(*FinalizeSampleRunResponse)(nil),     // 16: ah.v1.FinalizeSampleRunResponse
	(*EvaluateGCRequest)(nil),             // 17: ah.v1.EvaluateGCRequest
	(*EvaluateGCResponse)(nil),            // 18: ah.v1.EvaluateGCResponse
	(*GetSampleRunLifecycleRequest)(nil),  // 19: ah.v1.GetSampleRunLifecycleRequest
	(*GetSampleRunLifecycleResponse)(nil), // 20: ah.v1.GetSampleRunLifecycleResponse
}
var file_ah_v1_proto_depIdxs = []int32{
	8,  // 0: ah.v1.ArtifactRef.locations:type_name -> ah.v1.ArtifactLocation
	0,  // 1: ah.v1.RegisterArtifactRequest.artifact:type_name -> ah.v1.ArtifactRef
	3,  // 2: ah.v1.ResolveHandoffRequest.binding:type_name -> ah.v1.ArtifactBinding
	6,  // 3: ah.v1.ArtifactLocation.node_local:type_name -> ah.v1.NodeLocalLocation
	7,  // 4: ah.v1.ArtifactLocation.http:type_name -> ah.v1.HttpSource
	8,  // 5: ah.v1.MaterializationPlan.source_location:type_name -> ah.v1.ArtifactLocation
	8,  // 6: ah.v1.MaterializationCandidate.source_location:type_name -> ah.v1.ArtifactLocation
	10, // 7: ah.v1.MaterializationCandidate.conditions:type_name -> ah.v1.MaterializationCondition
	5,  // 8: ah.v1.ResolveHandoffResponse.placement_intent:type_name -> ah.v1.PlacementIntent
	9,  // 9: ah.v1.ResolveHandoffResponse.materialization_plan:type_name -> ah.v1.MaterializationPlan
	11, // 10: ah.v1.ResolveHandoffResponse.materialization_candidates:type_name -> ah.v1.MaterializationCandidate
	1,  // 11: ah.v1.ArtifactHandoffResolver.RegisterArtifact:input_type -> ah.v1.RegisterArtifactRequest
	4,  // 12: ah.v1.ArtifactHandoffResolver.ResolveHandoff:input_type -> ah.v1.ResolveHandoffRequest
	13, // 13: ah.v1.ArtifactHandoffResolver.NotifyNodeTerminal:input_type -> ah.v1.NotifyNodeTerminalRequest
	15, // 14: ah.v1.ArtifactHandoffResolver.FinalizeSampleRun:input_type -> ah.v1.FinalizeSampleRunRequest
	17, // 15: ah.v1.ArtifactHandoffResolver.EvaluateGC:input_type -> ah.v1.EvaluateGCRequest
	19, // 16: ah.v1.ArtifactHandoffResolver.GetSampleRunLifecycle:input_type -> ah.v1.GetSampleRunLifecycleRequest
	2,  // 17: ah.v1.ArtifactHandoffResolver.RegisterArtifact:output_type -> ah.v1.RegisterArtifactResponse
	12, // 18: ah.v1.ArtifactHandoffResolver.ResolveHandoff:output_type -> ah.v1.ResolveHandoffResponse
	14, // 19: ah.v1.ArtifactHandoffResolver.NotifyNodeTerminal:output_type -> ah.v1.NotifyNodeTerminalResponse
	16, // 20: ah.v1.ArtifactHandoffResolver.FinalizeSampleRun:output_type -> ah.v1.FinalizeSampleRunResponse
	18, // 21: ah.v1.ArtifactHandoffResolver.EvaluateGC:output_type -> ah.v1.EvaluateGCResponse
	20, // 22: ah.v1.ArtifactHandoffResolver.GetSampleRunLifecycle:output_type -> ah.v1.GetSampleRunLifecycleResponse
	17, // [17:23] is the sub-list for method output_type
	11, // [11:17] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ah_v1_proto_init() }
func file_ah_v1_proto_init() {
	if File_ah_v1_proto != nil {
		return
	}
	file_ah_v1_proto_msgTypes[8].OneofWrappers = []any{
		(*ArtifactLocation_NodeLocal)(nil),
		(*ArtifactLocation_Http)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ah_v1_proto_rawDesc), len(file_ah_v1_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ah_v1_proto_goTypes,
		DependencyIndexes: file_ah_v1_proto_depIdxs,
		MessageInfos:      file_ah_v1_proto_msgTypes,
	}.Build()
	File_ah_v1_proto = out.File
	file_ah_v1_proto_goTypes = nil
	file_ah_v1_proto_depIdxs = nil
}
