// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: ah_v1.proto

// Field number assignment rules (enforced from first consumer integration):
//   - Field numbers must never be reused within a message, even if the original field is removed.
//   - Removing a field requires reserving its number: reserve 3; reserve "old_field_name";
//   - Breaking changes require a new package (ah.v2) or an explicit pre-v1 reset documented in git.
//   - See docs/CONTRACT_OWNERSHIP.md for the full contract policy.

package ahv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArtifactHandoffResolver_RegisterArtifact_FullMethodName      = "/ah.v1.ArtifactHandoffResolver/RegisterArtifact"
	ArtifactHandoffResolver_AddSource_FullMethodName             = "/ah.v1.ArtifactHandoffResolver/AddSource"
	ArtifactHandoffResolver_UpdateSourceState_FullMethodName     = "/ah.v1.ArtifactHandoffResolver/UpdateSourceState"
	ArtifactHandoffResolver_ListSources_FullMethodName           = "/ah.v1.ArtifactHandoffResolver/ListSources"
	ArtifactHandoffResolver_VerifySource_FullMethodName          = "/ah.v1.ArtifactHandoffResolver/VerifySource"
	ArtifactHandoffResolver_ResolveHandoff_FullMethodName        = "/ah.v1.ArtifactHandoffResolver/ResolveHandoff"
	ArtifactHandoffResolver_NotifyNodeTerminal_FullMethodName    = "/ah.v1.ArtifactHandoffResolver/NotifyNodeTerminal"
	ArtifactHandoffResolver_FinalizeSampleRun_FullMethodName     = "/ah.v1.ArtifactHandoffResolver/FinalizeSampleRun"
	ArtifactHandoffResolver_EvaluateGC_FullMethodName            = "/ah.v1.ArtifactHandoffResolver/EvaluateGC"
	ArtifactHandoffResolver_GetSampleRunLifecycle_FullMethodName = "/ah.v1.ArtifactHandoffResolver/GetSampleRunLifecycle"
)

// ArtifactHandoffResolverClient is the client API for ArtifactHandoffResolver service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ArtifactHandoffResolverClient interface {
	RegisterArtifact(ctx context.Context, in *RegisterArtifactRequest, opts ...grpc.CallOption) (*RegisterArtifactResponse, error)
	AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*AddSourceResponse, error)
	UpdateSourceState(ctx context.Context, in *UpdateSourceStateRequest, opts ...grpc.CallOption) (*UpdateSourceStateResponse, error)
	ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error)
	VerifySource(ctx context.Context, in *VerifySourceRequest, opts ...grpc.CallOption) (*VerifySourceResponse, error)
	ResolveHandoff(ctx context.Context, in *ResolveHandoffRequest, opts ...grpc.CallOption) (*ResolveHandoffResponse, error)
	NotifyNodeTerminal(ctx context.Context, in *NotifyNodeTerminalRequest, opts ...grpc.CallOption) (*NotifyNodeTerminalResponse, error)
	FinalizeSampleRun(ctx context.Context, in *FinalizeSampleRunRequest, opts ...grpc.CallOption) (*FinalizeSampleRunResponse, error)
	EvaluateGC(ctx context.Context, in *EvaluateGCRequest, opts ...grpc.CallOption) (*EvaluateGCResponse, error)
	GetSampleRunLifecycle(ctx context.Context, in *GetSampleRunLifecycleRequest, opts ...grpc.CallOption) (*GetSampleRunLifecycleResponse, error)
}

type artifactHandoffResolverClient struct {
	cc grpc.ClientConnInterface
}

func NewArtifactHandoffResolverClient(cc grpc.ClientConnInterface) ArtifactHandoffResolverClient {
	return &artifactHandoffResolverClient{cc}
}

func (c *artifactHandoffResolverClient) RegisterArtifact(ctx context.Context, in *RegisterArtifactRequest, opts ...grpc.CallOption) (*RegisterArtifactResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterArtifactResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_RegisterArtifact_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) AddSource(ctx context.Context, in *AddSourceRequest, opts ...grpc.CallOption) (*AddSourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AddSourceResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_AddSource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) UpdateSourceState(ctx context.Context, in *UpdateSourceStateRequest, opts ...grpc.CallOption) (*UpdateSourceStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSourceStateResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_UpdateSourceState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) ListSources(ctx context.Context, in *ListSourcesRequest, opts ...grpc.CallOption) (*ListSourcesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSourcesResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_ListSources_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) VerifySource(ctx context.Context, in *VerifySourceRequest, opts ...grpc.CallOption) (*VerifySourceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifySourceResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_VerifySource_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) ResolveHandoff(ctx context.Context, in *ResolveHandoffRequest, opts ...grpc.CallOption) (*ResolveHandoffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResolveHandoffResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_ResolveHandoff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) NotifyNodeTerminal(ctx context.Context, in *NotifyNodeTerminalRequest, opts ...grpc.CallOption) (*NotifyNodeTerminalResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(NotifyNodeTerminalResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_NotifyNodeTerminal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) FinalizeSampleRun(ctx context.Context, in *FinalizeSampleRunRequest, opts ...grpc.CallOption) (*FinalizeSampleRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeSampleRunResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_FinalizeSampleRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) EvaluateGC(ctx context.Context, in *EvaluateGCRequest, opts ...grpc.CallOption) (*EvaluateGCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateGCResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_EvaluateGC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *artifactHandoffResolverClient) GetSampleRunLifecycle(ctx context.Context, in *GetSampleRunLifecycleRequest, opts ...grpc.CallOption) (*GetSampleRunLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSampleRunLifecycleResponse)
	err := c.cc.Invoke(ctx, ArtifactHandoffResolver_GetSampleRunLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArtifactHandoffResolverServer is the server API for ArtifactHandoffResolver service.
// All implementations must embed UnimplementedArtifactHandoffResolverServer
// for forward compatibility.
type ArtifactHandoffResolverServer interface {
	RegisterArtifact(context.Context, *RegisterArtifactRequest) (*RegisterArtifactResponse, error)
	AddSource(context.Context, *AddSourceRequest) (*AddSourceResponse, error)
	UpdateSourceState(context.Context, *UpdateSourceStateRequest) (*UpdateSourceStateResponse, error)
	ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error)
	VerifySource(context.Context, *VerifySourceRequest) (*VerifySourceResponse, error)
	ResolveHandoff(context.Context, *ResolveHandoffRequest) (*ResolveHandoffResponse, error)
	NotifyNodeTerminal(context.Context, *NotifyNodeTerminalRequest) (*NotifyNodeTerminalResponse, error)
	FinalizeSampleRun(context.Context, *FinalizeSampleRunRequest) (*FinalizeSampleRunResponse, error)
	EvaluateGC(context.Context, *EvaluateGCRequest) (*EvaluateGCResponse, error)
	GetSampleRunLifecycle(context.Context, *GetSampleRunLifecycleRequest) (*GetSampleRunLifecycleResponse, error)
	mustEmbedUnimplementedArtifactHandoffResolverServer()
}

// UnimplementedArtifactHandoffResolverServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArtifactHandoffResolverServer struct{}

func (UnimplementedArtifactHandoffResolverServer) RegisterArtifact(context.Context, *RegisterArtifactRequest) (*RegisterArtifactResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterArtifact not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) AddSource(context.Context, *AddSourceRequest) (*AddSourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddSource not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) UpdateSourceState(context.Context, *UpdateSourceStateRequest) (*UpdateSourceStateResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateSourceState not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) ListSources(context.Context, *ListSourcesRequest) (*ListSourcesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSources not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) VerifySource(context.Context, *VerifySourceRequest) (*VerifySourceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifySource not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) ResolveHandoff(context.Context, *ResolveHandoffRequest) (*ResolveHandoffResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveHandoff not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) NotifyNodeTerminal(context.Context, *NotifyNodeTerminalRequest) (*NotifyNodeTerminalResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method NotifyNodeTerminal not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) FinalizeSampleRun(context.Context, *FinalizeSampleRunRequest) (*FinalizeSampleRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeSampleRun not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) EvaluateGC(context.Context, *EvaluateGCRequest) (*EvaluateGCResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method EvaluateGC not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) GetSampleRunLifecycle(context.Context, *GetSampleRunLifecycleRequest) (*GetSampleRunLifecycleResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSampleRunLifecycle not implemented")
}
func (UnimplementedArtifactHandoffResolverServer) mustEmbedUnimplementedArtifactHandoffResolverServer() {
}
func (UnimplementedArtifactHandoffResolverServer) testEmbeddedByValue() {}

// UnsafeArtifactHandoffResolverServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArtifactHandoffResolverServer will
// result in compilation errors.
type UnsafeArtifactHandoffResolverServer interface {
	mustEmbedUnimplementedArtifactHandoffResolverServer()
}

func RegisterArtifactHandoffResolverServer(s grpc.ServiceRegistrar, srv ArtifactHandoffResolverServer) {
	// If the following call panics, it indicates UnimplementedArtifactHandoffResolverServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArtifactHandoffResolver_ServiceDesc, srv)
}

func _ArtifactHandoffResolver_RegisterArtifact_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterArtifactRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).RegisterArtifact(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_RegisterArtifact_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).RegisterArtifact(ctx, req.(*RegisterArtifactRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_AddSource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddSourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).AddSource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_AddSource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).AddSource(ctx, req.(*AddSourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_UpdateSourceState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSourceStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).UpdateSourceState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_UpdateSourceState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).UpdateSourceState(ctx, req.(*UpdateSourceStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_ListSources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSourcesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).ListSources(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_ListSources_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).ListSources(ctx, req.(*ListSourcesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_VerifySource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifySourceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).VerifySource(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_VerifySource_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).VerifySource(ctx, req.(*VerifySourceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_ResolveHandoff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveHandoffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).ResolveHandoff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_ResolveHandoff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).ResolveHandoff(ctx, req.(*ResolveHandoffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_NotifyNodeTerminal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NotifyNodeTerminalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).NotifyNodeTerminal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_NotifyNodeTerminal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).NotifyNodeTerminal(ctx, req.(*NotifyNodeTerminalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_FinalizeSampleRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeSampleRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).FinalizeSampleRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_FinalizeSampleRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).FinalizeSampleRun(ctx, req.(*FinalizeSampleRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_EvaluateGC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateGCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).EvaluateGC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_EvaluateGC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).EvaluateGC(ctx, req.(*EvaluateGCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ArtifactHandoffResolver_GetSampleRunLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSampleRunLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArtifactHandoffResolverServer).GetSampleRunLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArtifactHandoffResolver_GetSampleRunLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArtifactHandoffResolverServer).GetSampleRunLifecycle(ctx, req.(*GetSampleRunLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArtifactHandoffResolver_ServiceDesc is the grpc.ServiceDesc for ArtifactHandoffResolver service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArtifactHandoffResolver_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ah.v1.ArtifactHandoffResolver",
	HandlerType: (*ArtifactHandoffResolverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterArtifact",
			Handler:    _ArtifactHandoffResolver_RegisterArtifact_Handler,
		},
		{
			MethodName: "AddSource",
			Handler:    _ArtifactHandoffResolver_AddSource_Handler,
		},
		{
			MethodName: "UpdateSourceState",
			Handler:    _ArtifactHandoffResolver_UpdateSourceState_Handler,
		},
		{
			MethodName: "ListSources",
			Handler:    _ArtifactHandoffResolver_ListSources_Handler,
		},
		{
			MethodName: "VerifySource",
			Handler:    _ArtifactHandoffResolver_VerifySource_Handler,
		},
		{
			MethodName: "ResolveHandoff",
			Handler:    _ArtifactHandoffResolver_ResolveHandoff_Handler,
		},
		{
			MethodName: "NotifyNodeTerminal",
			Handler:    _ArtifactHandoffResolver_NotifyNodeTerminal_Handler,
		},
		{
			MethodName: "FinalizeSampleRun",
			Handler:    _ArtifactHandoffResolver_FinalizeSampleRun_Handler,
		},
		{
			MethodName: "EvaluateGC",
			Handler:    _ArtifactHandoffResolver_EvaluateGC_Handler,
		},
		{
			MethodName: "GetSampleRunLifecycle",
			Handler:    _ArtifactHandoffResolver_GetSampleRunLifecycle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ah_v1.proto",
}
