#!/usr/bin/env bash
# Self-test for proto-drift-check.sh. Each case commits a generated tree in a
# throwaway git repo, builds a separate "buf generate" output tree, runs the
# check against it and asserts PASS or FAIL, so a regression in the guard's
# scope (too broad or too narrow) fails CI.
set -euo pipefail

check="$(cd "$(dirname "$0")" && pwd)/proto-drift-check.sh"
work="$(mktemp -d)"
trap 'rm -rf "${work}"' EXIT

gen_dir="api/proto/ahv1"
go_file="${gen_dir}/ah_v1.pb.go"
grpc_file="${gen_dir}/ah_v1_grpc.pb.go"
failures=0

# go_src <protoc version> <doc comment>
go_src() {
  printf '// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n// \tprotoc-gen-go v1.36.11\n// \tprotoc        %s\n// source: ah_v1.proto\n\npackage ahv1\n\n// %s\ntype Artifact struct{}\n' "$1" "$2"
}

# grpc_src <protoc version>
grpc_src() {
  printf '// Code generated by protoc-gen-go-grpc. DO NOT EDIT.\n// versions:\n// - protoc-gen-go-grpc v1.6.1\n// - protoc             %s\n// source: ah_v1.proto\n\npackage ahv1\n' "$1"
}

doc="Deprecated: use protoc compiler output from ah.v2."

# new_case <name>: committed repo at ${work}/<name>/repo, and an identical
# generated tree at ${work}/<name>/gen that each case then mutates.
new_case() {
  local repo="${work}/$1/repo" gen="${work}/$1/gen"
  mkdir -p "${repo}/${gen_dir}" "${gen}/${gen_dir}"
  git -C "${repo}" init -q
  go_src v7.34.1 "${doc}" > "${repo}/${go_file}"
  grpc_src v7.34.1 > "${repo}/${grpc_file}"
  git -C "${repo}" add -A
  git -C "${repo}" -c user.name=t -c user.email=t@t commit -q -m init
  cp "${repo}/${go_file}" "${gen}/${go_file}"
  cp "${repo}/${grpc_file}" "${gen}/${grpc_file}"
  echo "${work}/$1"
}

expect() {
  local want="$1" name="$2" dir="$3" got
  if (cd "${dir}/repo" && "${check}" "${dir}/gen" >/dev/null 2>&1); then got=PASS; else got=FAIL; fi
  if [ "${got}" = "${want}" ]; then
    echo "ok   ${name}: ${got}"
  else
    echo "FAIL ${name}: want ${want}, got ${got}"
    failures=$((failures + 1))
  fi
}

d="$(new_case clean)"
expect PASS "clean tree" "${d}"

d="$(new_case unrelated-untracked)"
echo scratch > "${d}/repo/notes.txt"
mkdir -p "${d}/repo/tmp" && echo x > "${d}/repo/tmp/local.go"
expect PASS "unrelated untracked files are ignored" "${d}"

d="$(new_case header-only)"
go_src '(unknown)' "${doc}" > "${d}/gen/${go_file}"
grpc_src '(unknown)' > "${d}/gen/${grpc_file}"
expect PASS "protoc version header difference is tolerated" "${d}"

d="$(new_case stray-mismapped)"
mkdir -p "${d}/gen/github.com/HeaInSeo/artifact-handoff/${gen_dir}"
mv "${d}/gen/${go_file}" "${d}/gen/github.com/HeaInSeo/artifact-handoff/${go_file}"
expect FAIL "generated output outside api/proto/ahv1 (issue #30)" "${d}"

d="$(new_case new-output)"
grpc_src v7.34.1 > "${d}/gen/${gen_dir}/new_grpc.pb.go"
expect FAIL "uncommitted new generated file" "${d}"

d="$(new_case obsolete-output)"
rm "${d}/gen/${grpc_file}"
expect FAIL "committed file no longer generated (gRPC plugin removed)" "${d}"

d="$(new_case stale-code)"
printf 'var X = 1\n' >> "${d}/gen/${go_file}"
expect FAIL "stale committed generated code" "${d}"

d="$(new_case stale-comment)"
go_src v7.34.1 "Deprecated: use protoc compiler output from ah.v3." > "${d}/gen/${go_file}"
expect FAIL "stale doc comment mentioning protoc" "${d}"

if [ "${failures}" -ne 0 ]; then
  echo "::error::proto-drift-check self-test: ${failures} case(s) failed"
  exit 1
fi
echo "proto-drift-check self-test: all cases passed"
